theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = true # save when window looses focus
idle-timeout = 0
# original gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false # show hidden files as in starting with a dot
git-global = false # show files hidden by git globally

[keys.normal]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = ["collapse_selection", "keep_primary_selection", ":w"] # remove additional cursors and selections
y = "yank_joined_to_clipboard" # use my system clipboard
p = ["paste_clipboard_after", ":w"]
P = ["replace_selections_with_clipboard", ":w"] # paste over selection
d = ["yank_joined_to_clipboard", "delete_selection", ":w"] # add deleted text to system clipboaard
x = ["extend_line_below", "select_mode"] # go into select mode when you select line. This lets you undo going to far with x as well as more expected "c" behavour when combined with my select "c" mapping
";" = "flip_selections"
"," = "repeat_last_motion"

[keys.select]
pageup = "half_page_up"
pagedown = "half_page_down"
y = "yank_joined_to_clipboard"
p = ["replace_selections_with_clipboard", ":w"] # in select mode I always want to paste over my selection
P = ["replace_selections_with_clipboard", ":w"]
d = ["yank_joined_to_clipboard", "delete_selection", ":w"] # add deleted text to system clipboaard
c = ["trim_selections", "change_selection"] # when changing a line this stops the cursor moving to the beginning of the line underneath
";" = "flip_selections"
"," = "repeat_last_motion"

[keys.insert]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = [":w", "normal_mode"]

[keys.normal.space]
# Add comma to the end of the line
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ','",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
o = ":sh tmux popup"
n = ":sh tmux popup -E ranger"
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling giles raather than a file tree
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers
"=" = ":format"
"+" = ":indent-style 4"
"q" = ":q"
