theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = true
idle-timeout = 0
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false

[keys.normal]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = ["collapse_selection", "keep_primary_selection", ":w"]
y = "yank_joined_to_clipboard"
p = ["paste_clipboard_after", ":w"]
P = ["replace_selections_with_clipboard", ":w"]
d = ["yank_joined_to_clipboard", "delete_selection", ":w"]
x = ["extend_line_below", "select_mode"]
";" = "flip_selections"
"," = "repeat_last_motion"

[keys.select]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = ["normal_mode", "collapse_selection", "keep_primary_selection", ":w"]
y = "yank_joined_to_clipboard"
p = ["replace_selections_with_clipboard", ":w"]
P = ["replace_selections_with_clipboard", ":w"]
d = ["yank_joined_to_clipboard", "delete_selection", ":w"]
c = ["trim_selections", "change_selection"]
";" = "flip_selections"
"," = "repeat_last_motion"

[keys.insert]
pageup = "half_page_up"
pagedown = "half_page_down"
esc = [":w", "normal_mode"]

[keys.normal.space]
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ','",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
F = "file_picker_in_current_buffer_directory"
"." = ":toggle-option file-picker.git-ignore"
"=" = ":format"
"+" = ":indent-style 4"
